Config = {}

Config.Items = {

{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},
{
    item = "itemname",
    label = "Label here",
    limit = 10,
    can_remove = 1,
    type = "item_standard",
    usable = 1,
    useExpired = 0,
    groupId = 1,
    metadata = "{}",
    desc = "",
    degradation = 0,
    weight = 0.25
},

}
